on:
  push:
    branches:
      - main
name: release
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: node ./scripts/prerelease.js
      - name: create/update PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: regenerate docs/ and release/"
          branch: actions/prerelease
          delete-branch: true
          title: "chore: regenerate docs/ and release/"
          body: "`docs/` and `release/` are regenerated, by running `node ./scripts/prerelease.js`."
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: path-nice
          default-branch: main
          extra-files:
            - type: json
              path: release/package.json
              jsonpath: $.version
